### ISSUE TITLE
snap "core" is not available on stable for this architecture (armel)

### ISSUE THREAD

**Issue by prapador** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#47]
Hello, first, thank you very much for your work.

During the installation of RWSOLS V3, I have received the following error:

`snap "core" is not available on stable for this architecture (armel) but exists on other architectures (amd64, arm64, armhf, i386, ppc64el, s390x).`

I am using a Raspberry Pi Zero

Thanks a lot!

**Comment by dontwatchthisspace** [comment]
Not sure if it helps, but I've received this same issue on a Raspberry Pi Zero as well, and a Raspberry Pi Model B Rev 2.

**Comment by sciguy14** [comment]
Sorry, but the snap store doesn't have support for the older instruction sets. You may need to use a newer Pi that is is on the ARMv8-A instruction set (see here: https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications).

Alternatively, you can modify the setup script to use apt versions of the snap apps I am using, but I used the snap apps because i had trouble getting the apt versions to behave properly.
