### ISSUE TITLE
Flush empty buffer

### ISSUE THREAD

**Issue by smark91** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#9]
in index.php:

change:
```php
ob_end_flush();
```
with:
```php
if (ob_get_level()>1) {ob_end_flush();}
```

avoid flushing empty buffer (on x-debug it make an error).

**Comment by sciguy14** [comment]
@smark91 When I did this, it resulted in no dynamic flushing of the current state - that's undesirable. What is the error that you're seeing? I don't get any errors.

**Comment by smark91** [comment]
This is the x-debug error I have.

![flush](https://cloud.githubusercontent.com/assets/11672481/9997924/11d20d6a-608f-11e5-852c-aea988eb274a.jpg)

**Comment by sciguy14** [comment]
@smark91 Are actually experiencing functionality problems because of this? What you're described is a notice, not an error. Attempting to flush an empty buffer shouldn't have any effect on the programs functionality, and making the change you recommended makes flushing fail entirely. I'm closing this for now
